name: ssh-into-aws-ec2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: "us-east-1"
  REMOTE_HOST: "ec2-44-204-193-68.compute-1.amazonaws.com"
  REMOTE_USER: "ubuntu"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key.pem
          chmod 600 ~/.ssh/github-actions-key.pem
          cd ~/.ssh/
          ssh -tt -i "github-actions-key.pem" -o UserKnownHostsFile=~/.ssh/known_hosts ubuntu@ec2-44-204-193-68.compute-1.amazonaws.com
          ls
        env:
          SSH_HOST: ${{ env.REMOTE_HOST }}
          SSH_USER: ${{ env.REMOTE_USER }}
          SSH_KEY: ${{ secrets.EC2_KEY }} 
      - name: List home directory
        run: ssh ec2 'ls -la'
